### ISSUE TITLE
Change profileEdition to display the SPTarkov Edition instead of EFT edition

### ISSUE THREAD

**Issue by Propet40** [minihazel/SPTMiniLauncher#1]
Hi,

Instead of being limited to the four editions provided by default Tarkov, it makes more sense for the mod manager to utilize the growing number of SPTarkov editions. This would allow for displaying of special editions like "SPT Developer" and "SPT Zero to Hero".

Modifying line 850 in form1.cs to 
`string profileEdition = json["info"]["edition"].ToString();`

Afterwards removing the Switch statement and directly applying the String value
`lblProfileEdition.Text = profileEdition;`

I have tested this in my own copy of the project and believe it makes more sense than the previous iteration.

**Comment by minihazel** [comment]
Hi there,

I'm pretty sure you are commenting on the wrong project. The Mini Launcher does not touch profiles in the slightest. Are you perhaps trying to comment on the Native SPT Manager I made? This app is not designed to access the Tarkov editions, or any profiles, which is what causes me to wonder why you opened this issue.

**Comment by Propet40** [comment]
You're right! I apologize, clearly had too many tabs open that day. Joined Github just recently, still getting used to it.

**Comment by Propet40** [comment]
Do you wish for me to open a new issue on the Native SPT Manager in that case?

**Comment by minihazel** [comment]
Yes please. From what I can see it is a good idea, and I'll get to it as soon as I have time to finish the upcoming update.

**Comment by Propet40** [comment]
Alright! Have done so!
