### ISSUE TITLE
[Suggestion/Request] Modifiable Third Party Section

### ISSUE THREAD

**Issue by MusicManiac** [minihazel/SPTMiniLauncher#2]
Would be nice if third-party apps section was 

1. Scrollable
2. Modifiable

What I mean by modifiable, is config file where people could put a path to an .exe so it's displayed in the list.
something like
```
Third-Party Apps : [
	{
		"Path": "C:/SPT/folder1/newtool.exe"
		"Name": "New Tool"
	},
	{
		"Path": "whatever it is here now"
		"Name" : "SVM"
	}
]
```

**Comment by minihazel** [comment]
Definitely doable, I'll look into it!

**Comment by minihazel** [comment]
This functionality has now been implemented on both points. Update 3.0 will go live later today, feel free to leave feedback when it does.

### Preview of Third Party Apps section with custom names:

![SPT_Launcher_FOBeBp3kEx](https://github.com/minihazel/SPTMiniLauncher/assets/52471176/f85fa74c-8dc9-43db-bcda-557efadcded5)
